### ISSUE TITLE
Armor model is broken for other mobs

### ISSUE THREAD

**Issue by tesseract-two** [shizotoaster/ultimate-armor-patch#1]
![huge_2023-03-12_16 25 37](https://user-images.githubusercontent.com/118913639/224571543-2ac731da-3589-465d-9a67-cdeffd95c11d.png)
This also happens with skeletons, wither skeletons, drowned, husks, strays, piglins, zombie piglins, and piglin brutes. This might be a lot of effort to fix unfortunately.

**Comment by shizotoaster** [comment]
Thank you for the report, will be fixed asap!

**Comment by shizotoaster** [comment]
Fixed in 2.0.0
